[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mysql]
command=/usr/sbin/mysqld
user=mysql
autostart=true
autorestart=true
stderr_logfile=/var/log/mysql.err.log
stdout_logfile=/var/log/mysql.out.log

[program:php-fpm]
command=/usr/sbin/php-fpm8.3 -F
autostart=true
autorestart=true

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true
stderr_logfile=/var/log/apache.err.log
stdout_logfile=/var/log/apache.out.log

[program:alert-micro]
command=node server.js
directory=/app/micro/alert
autostart=true
autorestart=true
stderr_logfile=/var/log/alert-micro.err.log
stdout_logfile=/var/log/alert-micro.out.log

[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
directory=/var/lib/redis
user=root
autostart=true
autorestart=true
startsecs=1
stopsignal=TERM
stdout_logfile=/var/log/redis.err.log
stderr_logfile=/var/log/redis.out.log

[program:cron]
command=cron -f
stdout_logfile=/var/log/cron.err.log
stderr_logfile=/var/log/cron.out.log
autorestart=true
user=root